### ISSUE TITLE
Questions about Sign Up requirements 

### ISSUE THREAD

**Issue by yaels818** [orellazri/ourstreets#1]
For the https://github.com/orellazri/ourstreets/wiki/Testing#04---sign-up-process-negative-test

We need to be sure about a few points:

1. Which fields are mandatory (*)? 
We have Full Name, Phone, Email, Password, but is Phone mandatory? 
2.  We should insert some sort of labels in the sign up screen about with fields are (*), and maybe a (?) with a pop up explanation or something about why we need this information. 
3. Are there any checks on the name field? For example, can one word pass as a name?
4. Any checks for Phone or Email? 
5. Any checks for Password regarding which keys you can use or minimum length

<img width="250" src="https://user-images.githubusercontent.com/32670283/158579768-1114029b-b720-4453-a8ae-4186b19b1586.png" /> | <img width="250" src="https://user-images.githubusercontent.com/99403939/166904948-bb83a98a-52ef-4b91-9baf-7f5c7207e47c.png" />

**Comment by orellazri** [comment]
1. All of the fields are mandatory (email, password, full name, phone number)
2. I'm not sure about (*) since everything is mandatory, and it's pretty self explanatory why the other fields are needed, but it's possible to add an info label/button if the organization would want that.
3. Currently there are no checks, but it could be a good idea to check the validity of the field - Only letters in Hebrew/English.
4. Not currently, but should be implemented.
5. None, but I think a minimum of 5 letters could be good. What's your thoughts?

**Comment by yaels818** [comment]
Thanks for all the additions! 

This is a summary of what we discussed today:

2. Agreed, no need for (*) but we do need to write something about the phone number so users would know what to expect - a phone call about their complaint? sms messages? Also, the person who reports the hazard might not be the one who actually saw it - like if a child/elderly person asked for someone to report for them.
3. Phone validation - no less than 9 digits, no more than 11
